version: "3.9"

services:
  ova-task-api:
    container_name: ova-task-api
    build: .
    ports:
      - "8081:8081"
    restart: unless-stopped
  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/docker/volumes/postgres/_data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ova_task_api
      PGDATA: /var/lib/docker/volumes/postgres/_data/pgdata
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080